# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: meghribe <meghribe@student.42barcelon      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/10/27 17:03:55 by meghribe          #+#    #+#              #
#    Updated: 2025/10/27 17:24:37 by meghribe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = changethislater
CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -fsanitize=address -g
SRCS= main.cpp
OBJS= main.o

.PHONY: all
all: $(NAME)

$(NAME): 

.PHONY: clean
clean:
	rm -f $(OBJS)

.PHONY: fclean
fclean: clean
	rm -f $(NAME)

.PHONY: re
re:
	fclean all
